name: sudoku_app
description: Simply sudoku app by fudeo corse

version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: '>=2.19.6'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sudoku_solver_generator: ^2.1.0+1
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.5
  collection: ^1.17.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash1.svg
    - assets/splash2.svg
    - assets/splash3.svg